# 知识库系统配置文件

# 环境配置
environment: development
debug: true

# 数据库配置
database:
  url: "sqlite+aiosqlite:///data/knowledge_base.db"
  echo: false

# 同步配置
sync:
  schedule: "0 */6 * * *"  # 每6小时同步一次
  auto_update_nav: true
  docs_output_dir: "packages/docs/docs"
  nav_script_path: "packages/docs/scripts/update_nav.py"

# 搜索配置
search:
  engine: "whoosh"
  index_path: "data/search_index"
  chinese_analyzer: true
  min_word_len: 1

# API服务配置
api:
  host: "0.0.0.0"
  port: 8080
  cors_origins:
    - "https://claude.ai"
    - "https://localhost:3000"
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  rate_limit: "100/minute"

# MCP服务配置
mcp:
  host: "0.0.0.0"
  port: 9000
  max_connections: 100

# 日志配置
logging:
  level: "INFO"
  format: "json"
  file: "logs/app.log"